server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
server/src/main/java/com/seb028/guenlog/member/dto/MyPageInfoDto.java
server/src/main/java/com/seb028/guenlog/member/entity/MemberWeight.java
server/src/main/java/com/seb028/guenlog/member/mapper/MyPageInfoMapper.java
server/src/main/java/com/seb028/guenlog/member/service/MemberWeightService.java
server/src/main/java/com/seb028/guenlog/member/service/MyPageService.java
server/src/main/java/com/seb028/guenlog/member/util/MyPageInfo.java

- 개인정보 수정을 위한  MyPageInfo 클래스 추가
- MyPageInfoDto에 수정용 DTO 클래스 추가
- MyPageInfoMapper에 Patch DTO 클래스와 MyPage간 변환 메서드 추가 
- MyPageController에 개인 정보 수정 기능 메서드 추가
- MemberWeight 클래스에 설정 메서드 추가 
- MemberWeightService 클래스에 메서드 추가 
- MyPageService 클래스에 메서드 추가

:sparkles:  마이 페이지 개인 정보 수정 기능

---

server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
server/src/main/java/com/seb028/guenlog/member/dto/MyPageInfoDto.java
server/src/main/java/com/seb028/guenlog/member/mapper/MyPageInfoMapper.java

Member 클래스 수정과 SingleResponseDto 추가로 인한 기존 코드 변경

🎨 Member 클래스 수정과 SingleResponseDto 추가로 인한 기존 코드 변경 

---

server/src/main/java/com/seb028/guenlog/exception/ExceptionCode.java
server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
server/src/main/java/com/seb028/guenlog/member/dto/PasswordPatchDto.java
server/src/main/java/com/seb028/guenlog/member/mapper/MyPageInfoMapper.java
server/src/main/java/com/seb028/guenlog/member/service/MyPageService.java

- 비밀번호 변경 PatchDTO 클래스 추가
- MyPageController 클래스에서 비밀번호 변경하는 메서드 추가
- MyPageService 클래스에서 비밀번호 변경을 위한 메서드, 변수 추가
- ExceptionCode 클래스에 비밀번호 불일치에 대한 Exception Code 추가

✨ 마이페이지에서 비밀번호 변경하는 기능

---

client/src/pages/Workout.jsx

// 운동진행리스트 state 업데이트 문제
// useref로 리스트 파악 문제

🐛  workout 버그명시

---

server/src/main/java/com/seb028/guenlog/exercise/repository/TodayRepository.java
server/src/main/java/com/seb028/guenlog/member/controller/MyPageController.java
server/src/main/java/com/seb028/guenlog/member/dto/MyPageResponseDto.java
server/src/main/java/com/seb028/guenlog/member/mapper/MyPageMapper.java
server/src/main/java/com/seb028/guenlog/member/repository/MemberWeightRepository.java
server/src/main/java/com/seb028/guenlog/member/service/MyPageService.java
server/src/main/java/com/seb028/guenlog/member/util/MonthlyRecord.java
server/src/main/java/com/seb028/guenlog/member/util/MonthlyWeight.java
server/src/main/java/com/seb028/guenlog/member/util/MyPage.java

- MyPageController 클래스에 메서드 추가
- MyPageService 클래스에 메서드 추가
- TodayRepository 클래스에 메서드 추가
- MemberWeightRepository 클래스에 메서드 추가
- util 패키지 내부 한달 동안 운동 기록, 한달 몸무게 저장하는 MonthlyRecord, MonthlyWeight 클래스 생성
- MyPage 클래스 추가
- MyPageResponseDto 클래스 추가
- MyPageMapper 인터페이스 추가

:sparkles: 마이 페이지 접속시 최근 운동기록, 몸무게 기록 확인하는 첫 페이지 기능

---

server/src/main/java/com/seb028/guenlog/member/dto/MyPageInfoDto.java

- MyPageInfoDto 클래스 내부 Patch클래스에 nickname, age, height, weight 유효성 검사 추가

:bug: 마이 페이지에서 개인 정보 수정시 개인정보에 대한 유효성 검사 추가

---

server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseProgressController.java
server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressResponseDto.java
server/src/main/java/com/seb028/guenlog/exercise/mapper/ExerciseProgressMapper.java
server/src/main/java/com/seb028/guenlog/exercise/service/ExerciseProgressService.java
server/src/main/java/com/seb028/guenlog/exercise/util/ExerciseProgress.java

- 하루 운동 내역, 운동 목록들을 담은 ExerciseProgress 클래스 구현
- ExerciseProgressResponseDto 클래스 구현
- ExerciseProgress 클래스, DTO 클래스 간 변환할 ExerciseProgressMapper 클래스 구현
- ExerciseProgress 객체를 ResponseDto 클래스로 변환시키는 메서드 구현
- 운동 진행 관련 ExerciseProgressController 클래스 구현
- 운동 진행 관련 ExerciseProgressService 클래스 구현
- ExerciseProgressController 클래스 내부 운동 진행시 오늘 운동 목록 조회하는 메서드 구현
- ExerciseProgressService 클래스 내부 운동 진행시 오늘 운동 목록 조회하는 메서드 구현

✨ 운동 진행에서 운동 목록 불러오는 기능

---

server/src/main/java/com/seb028/guenlog/config/SecurityConfig.java
server/src/main/java/com/seb028/guenlog/config/auth/handler/MemberAuthenticationSuccessHandler.java
server/src/main/java/com/seb028/guenlog/member/dto/LoginDto.java
server/src/main/java/com/seb028/guenlog/member/dto/MemberDto.java
server/src/main/java/com/seb028/guenlog/member/service/MemberService.java

- 최초 로그인 했을 때 ResponseBody에 객체의 모든 필드를 출력하도록 되어 있습니다.
해당 부분에 대해서 추후 리팩터링이 필요합니다.

🐛 사용자 최초 로그인 상태 ResponseBody에 출력

---

server/src/main/java/com/seb028/guenlog/exception/ExceptionCode.java
server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseProgressController.java
server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressPatchDto.java
server/src/main/java/com/seb028/guenlog/exercise/entity/Today.java
server/src/main/java/com/seb028/guenlog/exercise/mapper/ExerciseProgressMapper.java
server/src/main/java/com/seb028/guenlog/exercise/service/ExerciseProgressService.java

- 운동 완료 수정용 ExerciseProgressPatchDto 클래스 구현
- PatchDto클래스를 운동 진행 객체 ExerciseProgress 클래스로 변환하는 메서드를 ExerciseProgressMapper에 추가
- Today 클래스에서 총 운동시간 수정하는 메서드 추가
- 운동 진행 ExerciseProgressController 클래스에 운동 완료하는 수정 patch메서드 추가
- 운동 진행 ExerciseProgressService 클래스에서 운동 완료하는 수정 update 메서드 추가
- 운동 기록 목록이 존재하지 않는 경우의 Exception code 추가

✨ 운동 진행에서 운동 완료하는 기능

---

server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseProgressController.java
server/src/main/java/com/seb028/guenlog/exercise/repository/TodayRepository.java
server/src/main/java/com/seb028/guenlog/member/dto/MyPageResponseDto.java
server/src/main/java/com/seb028/guenlog/member/mapper/MyPageMapper.java
server/src/main/java/com/seb028/guenlog/member/util/MonthlyRecord.java
server/src/main/java/com/seb028/guenlog/member/util/MonthlyWeight.java

- ExerciseProgressController 클래스에서 조회 메서드 리턴시 ResponseEntity에 제네릭 추가
- ExerciseProgressController 클래스에서 수정 메서드 PathVariable 수정
- TodayRepository 클래스에서 최근 6개월 운동기록 쿼리 수정
- MonthlyRecord, MonthlyWeight Repository 쿼리에 맞게 인터페이스 반환 값 변경 후 메서드 추가
- MonthlyRecord, MonthlyWeight 클래스에서 필요없는 import문 삭제, 주석 추가, 날짜 변수를 문자열로 수정
- MyPageMapper 클래스에서 MyPage클래스에서 MyPageResponseDto로 변환하는 메서드 추가
- MyPageResponseDto의 MonthlyRecordDto, MonthlyWeightDto 추가

:bug: 마이페이지 접속시 운동 기록, 몸무게 기록 조회하는 기능에서 조회안되는 에러 수정, 그외 기타 코드 수정

---

server/src/main/java/com/seb028/guenlog/exercise/controller/ExerciseProgressController.java
server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressPatchDto.java
server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressResponseDto.java
server/src/main/java/com/seb028/guenlog/exercise/mapper/ExerciseProgressMapper.java
server/src/main/java/com/seb028/guenlog/exercise/service/ExerciseProgressService.java

- ExerciseProgressResponseDto클래스의 변수들 타입을 래퍼 클래스로 변경
- ExerciseProgressPatchDto 클래스에서 변수들 타입을 래퍼 클래스로 변경
- ExerciseProgressMapper 클래스에서 patchDto 변환 메서드에 completed 메서드 변경
- ExerciseProgressController 클래스에서 운동 진행 완료 메서드에 PathVariable 수정
- ExerciseProgressService 클래스에서 운동진행 완료 메서드에 운동 기록 목록 조회 코드 수정

:bug: 운동 진행 목록 조회, 운동 완료 기능시 에러 수정

---

server/src/main/java/com/seb028/guenlog/member/entity/Member.java

member_weight 코드 머지 이후 회원 삭제 기능 안되는 버그 픽스

:bug: 회원 탈퇴를 위한 연관관계 맵핑

---

server/src/test/java/com/seb028/guenlog/GuenLogApplicationTests.java
server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java

- com.seb028 패키지 안에 guenlog 패키지 생성
- com.seb028.guenlog 패키지 안에 Test 클래스 이동

:truck: ApplicationTest 클래스, ControllerTest 클래스 패키지 이동

---

client/src/components/Map/Map.jsx
client/src/components/Mypage/MyPageFirst.jsx
client/src/components/Mypage/MyPageSecond.jsx
client/src/components/Mypage/MyPageText.jsx
client/src/components/Mypage/PwModal.jsx
client/src/components/Mypage/SecessionModal.jsx

🎨axios 수정 완료

---

server/src/docs/asciidoc/index.adoc
server/src/main/resources/static/docs/index.html
server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
server/src/test/java/com/seb028/util/ApiDocumentUtils.java

- ExerciseProgressControllerRestDocsTest 클래스에 운동 진행 조회 테스트 메서드 구현
- responseBody, request body 를 잘 표현하게 해줄 API 문서화 유틸 ApiDocumentUtils 인터페이스 구현
- ExerciseProgressControllerRestDocsTest 클래스에 운동 진행 조회 테스트 코드에 HTTP 요청시에 대한 헤더 추가
- Rest doc API 문서 index.adoc 생성
- index.adoc 파일 오타 수정
- Spring Rest Docs API문서 HTML파일 생성
- 운동 진행 조회 API index.adoc에 내용 추가
- 불필요한 import 문 제거
- 주석 추가

✅ 운동 진행 조회 - Controller 테스트, Spring Rest Docs을 이용한 API 문서화

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/com/seb028/guenlog/exercise/dto/ExerciseProgressPatchDto.java
server/src/main/resources/static/docs/index.html
server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java

- ExerciseProgressControllerRestDocsTest 클래스에 운동 진행 완료 테스트 메서드 구현
- 테스트를 위해 ExerciseProgressPatchDto클래스에 Builder 어노테이션 추가
- index.adoc파일에 운동 진행 완료 API 내용 추가
- 운동진행완료 API 내용 추가후 index.html 새로 생성

✅ 운동 진행 완료 - Controller 테스트, Spring Rest Docs을 이용한 API 문서화

---

server/src/docs/asciidoc/index.adoc
server/src/main/resources/static/docs/index.html
server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java

- MyPageControllerRestDocsTest 클래스 구현
- MyPageControllerRestDocsTest 클래스 내 마이페이지 조회 테스트 메서드 구현
- index.adoc파일에 마이페이지 조회 API 내용 추가
- 마이페이지 조회 API 내용 추가후 index.html 새로 생성

✅ 마이페이지 조회 API - Controller 테스트, Spring Rest Docs을 이용한 API 문서화

---

server/src/main/java/com/seb028/guenlog/config/SecurityConfig.java
server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java

- Oauth2 로그인 시 페이지 이동이 없는 버그 픽스
- Oauth2 로그인 성공시 쿼리로 토큰, 최초 로그인 상태 전송
- http://localhost:3000/login/oauth 로 리다이렉트

:bug: Oauth2 로그인 성공시 쿼리로 토큰, 최초 로그인 상태 전송

---

server/src/docs/asciidoc/index.adoc
server/src/main/resources/static/docs/index.html
server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java

- MyPageControllerRestDocsTest 클래스에 마이페이지 개인 정보 조회 테스트 메서드 작성
- index.adoc파일에 마이페이지 개인정보 조회 API 내용 추가
- 마이페이지 개인정보 조회 API 내용 추가후 index.html 새로 생성

:memo: 마이페이지 개인 정보 조회 Controller 테스트 코드 작성 및 Spring Rest Docs API 문서에 마이페이지 개인 정보 조회 API 내용 추가

---

server/src/docs/asciidoc/index.adoc
server/src/main/resources/static/docs/index.html
server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java

- ExerciseProgressControllerRestDocsTest클래스에서 각 테스트 메서드들에서 대문자 제거
- MyPageControllerRestDocsTest클래스에서 각 테스트 메서들에서 대문자 제거
- 새로 테스트 진행 후 index.adoc 스니펫 수정, 문서 버전 변경
- index.html 새로 빌드

:bug: 서버 배포시 RestDocs Unresolved Error로 인한 코드 수정

---

server/src/docs/asciidoc/index.adoc
server/src/main/resources/static/docs/index.html
server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java

- MyPageControllerRestDocsTest 클래스에 마이페이지 개인 정보 수정 테스트 메서드 작성
- index.adoc파일에 마이페이지 개인정보 수정 API 내용 추가
- 마이페이지 개인정보 수정 API 내용 추가후 index.html 새로 생성

:memo: 마이페이지 개인 정보 수정 Controller 테스트 코드 작성 및 Spring Rest Docs API 문서에 마이페이지 개인 정보 수정 API 내용 추가

---

server/src/docs/asciidoc/index.adoc
server/src/main/java/com/seb028/guenlog/member/dto/PasswordPatchDto.java
server/src/main/resources/static/docs/index.html
server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java

- 마이페이지 비밀번호 수정 테스트위해 PasswordPatchDto 클래스에 @Builder 어노테이션 추가
- MyPageControllerRestDocsTest 클래스에 마이페이지 비밀번호 수정 테스트 메서드 작성
- index.adoc파일에 마이페이지 비밀번호 수정 API 내용 추가
- 마이페이지 비밀번호 수정 API 내용 추가후 index.html 새로 생성

:memo: 마이페이지 비밀번호 수정 Controller 테스트 코드 작성 및 Spring Rest Docs API 문서에 마이 페이지 비밀번호 수정 API 내용 추가

---

server/src/test/java/com/seb028/guenlog/restdocs/exercise/ExerciseProgressControllerRestDocsTest.java
server/src/test/java/com/seb028/guenlog/restdocs/member/MyPageControllerRestDocsTest.java

- ExercisesProgressControllerRestDocsTest클래스의 메서드들에 ResponseBody 검증 테스트 추가
- MyPageControllerRestDocsTest클래스의 메서드들에 ResponseBody 검증 테스트 추가

:white_check_mark:운동 진행 조회/완료, 마이페이지 조회, 개인정보 조회, 수정 테스트시 ResponseBody 검증 테스트 추가

---

server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java

- 프론트 임시 배포 서버 주소로 OAuth2 리다이렉트 URI 수정

🔧 프론트 임시 배포 서버 주소로 OAuth2 리다이렉트 URI 수정

---

server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java

- 프론트 최종 배포 주소로 OAuth2 리다이렉트 URI 수정

🔧 프론트 최종 배포 서버 주소로 OAuth2 리다이렉트 URI 수정

---

server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java

:ambulance: OAuth2 최초 로그인 작동 에러로 인해 로컬 주소로 리다이렉트

:ambulance: OAuth2 최초 로그인 작동 에러로 인해 로컬 주소로 리다이렉트

---

server/src/main/java/com/seb028/guenlog/config/auth/handler/Oauth2MemberSuccessHandler.java
server/src/main/java/com/seb028/guenlog/exercise/entity/Record.java
server/src/main/java/com/seb028/guenlog/exercise/entity/Today.java
server/src/main/java/com/seb028/guenlog/member/entity/Member.java

- 운동 계획 존재할 때 회원 탈퇴 안되는 버그 픽스
-> 연관 관계 수정
- OAuth2 리다이렉트 URI 프론트 서버 배포 주소로 수정

🚑운동 계획 존재할 때 회원 탈퇴 안되는 버그 픽스, OAuth2 리다이렉트 URI 수정
